# Generated by Django 3.2 on 2021-04-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='mobileno',
            field=models.CharField(default='000000000000', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='nightstay',
            field=models.IntegerField(default='1'),
        ),
    ]
