# Generated by Django 3.2 on 2021-04-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20210425_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guests',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileno',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
