# Generated by Django 3.2 on 2021-04-25 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_user_intime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='paymethod',
            field=models.CharField(default='Cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
