# Generated by Django 3.2 on 2021-04-26 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_auto_20210426_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 12, 59, 57, 103336)),
        ),
    ]
