# Generated by Django 3.2 on 2021-04-26 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_auto_20210426_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 13, 16, 59, 876019)),
        ),
    ]
