# Generated by Django 3.2 on 2021-04-26 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_auto_20210426_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='myimage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 17, 55, 12, 583833)),
        ),
        migrations.AlterField(
            model_name='user',
            name='outtime',
            field=models.DateTimeField(null=True),
        ),
    ]
