# Generated by Django 3.2 on 2021-04-26 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_auto_20210426_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 22, 39, 5, 204880)),
        ),
        migrations.AlterField(
            model_name='user',
            name='outtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 22, 39, 5, 204880)),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/myimage/AK.jpg', upload_to='myimage'),
        ),
    ]
