# Generated by Django 3.2 on 2021-04-27 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0014_auto_20210427_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.BooleanField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 12, 8, 11, 68021)),
        ),
        migrations.AlterField(
            model_name='user',
            name='outtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 12, 8, 11, 68021)),
        ),
    ]
