# Generated by Django 3.2 on 2021-04-27 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0015_auto_20210427_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.BooleanField(choices=[('May', 'May'), ('Pay', 'Pay'), ('Say', 'Say')], default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 12, 13, 55, 476069)),
        ),
        migrations.AlterField(
            model_name='user',
            name='outtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 12, 13, 55, 476069)),
        ),
    ]
