# Generated by Django 3.2 on 2021-04-27 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0016_auto_20210427_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 12, 27, 37, 199535)),
        ),
        migrations.AlterField(
            model_name='user',
            name='outtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 12, 27, 37, 199535)),
        ),
        migrations.AlterField(
            model_name='user',
            name='paymethod',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('PhonePay', 'PhonePay'), ('Net Banking', 'Net Banking'), ('UPI ID', 'UPI ID'), ('Paytm', 'Paytm')], default='--Select--', max_length=100),
        ),
    ]
