# Generated by Django 3.2 on 2021-04-27 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0017_auto_20210427_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 14, 22, 57, 282383)),
        ),
        migrations.AlterField(
            model_name='user',
            name='outtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 14, 22, 57, 282383)),
        ),
    ]
