# Generated by Django 3.2 on 2021-04-27 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0018_auto_20210427_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='I agree to the T&C'),
        ),
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 23, 27, 4, 833525)),
        ),
        migrations.AlterField(
            model_name='user',
            name='outtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 23, 27, 4, 833525)),
        ),
    ]
