# Generated by Django 3.2 on 2021-04-29 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0019_auto_20210427_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.CharField(default='--Select--', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 11, 23, 56, 203671)),
        ),
        migrations.AlterField(
            model_name='user',
            name='outtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 11, 23, 56, 203671)),
        ),
    ]
