# Generated by Django 3.2 on 2021-04-29 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0021_auto_20210429_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='indate',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 16, 51, 18, 305697)),
        ),
        migrations.AlterField(
            model_name='user',
            name='intime',
            field=models.TimeField(default=datetime.datetime(2021, 4, 29, 16, 51, 18, 305697)),
        ),
        migrations.AlterField(
            model_name='user',
            name='outdate',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 16, 51, 18, 305697)),
        ),
        migrations.AlterField(
            model_name='user',
            name='outtime',
            field=models.TimeField(default=datetime.datetime(2021, 4, 29, 16, 51, 18, 305697)),
        ),
    ]
